apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prism-api.fullname" . }}
  labels:
    {{- include "prism-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prism-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prism-api.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PRISM_API_PORT
              value: {{ .Values.env.apiPort | quote }}
            - name: PRISM_CORS_ORIGIN
              value: {{ .Values.env.corsOrigin | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
