DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_USER}') THEN
    CREATE ROLE ${APP_USER} WITH LOGIN PASSWORD '${APP_PASSWORD}';
  ELSE
    ALTER ROLE ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
  END IF;
END
$$;

GRANT CONNECT ON DATABASE ${DB} TO ${APP_USER};
