CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS prism;

GRANT USAGE ON SCHEMA core TO ${APP_USER};
GRANT USAGE ON SCHEMA prism  TO ${APP_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO ${APP_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA prism  TO ${APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA core
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA prism
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA core
  GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA prism
  GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
