# PostgreSQL standby server configuration
# This file is used to configure the standby PostgreSQL server in a replication setup.

listen_addresses = '*'
log_timezone = 'Asia/Seoul'
hba_file = '/etc/postgresql/pg_hba.conf'