# PostgreSQL primary server configuration
# This file is used to configure the primary PostgreSQL server in a replication setup.

listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB
max_wal_senders = 10
max_replication_slots = 10
log_timezone = 'Asia/Seoul'
hba_file = '/etc/postgresql/pg_hba.conf'